#!/usr/bin/ruby
#
# populate_mimetypes.rb
#

require 'rubygems'

ENV['RAILS_ENV'] ||= 'development'
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")

Mimetype.collection.drop
Fileextension.collection.drop

count = 0

File.open('/etc/mime.types').each do |l|
  next if l[0,1] == '#'
  elements = l.strip.split(' ')
  mimetype = elements.shift
  ext_ids = []
  elements.each do |ext|
    f_ext = Fileextension.new(:name => ext.downcase)
    ext_ids << f_ext
  end
  mimetype = Mimetype.new(:name => mimetype)
  mimetype.fileextensions = ext_ids # this sets mimetype_id in Fileextension
  mimetype.save
  ext_ids.each { |e| e.save } # save Fileextensions
  count += 1
end

puts "Saved #{count} mimetypes"
