#!/usr/bin/ruby
#
# populate_mimetypes.rb
#

require 'rubygems'

ENV['RAILS_ENV'] ||= 'development'
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")

File.open('/etc/mime.types').each do |l|
  next if l[0,1] == '#'
  l.strip.match(/([^\s]+)\s+((([^\s]+)(\s+)?)+)/) do |matchdata|
    mimetype = matchdata[1]
    extensions = matchdata[2].split(' ')
    ext_ids = []
    extensions.each do |ext|
      ext_ids << Fileextension.new(:name => ext)
    end
    mimetype = Mimetype.new(:name => mimetype, :fileextensions => ext_ids)
    puts "Mimetype #{mimetype} with #{ext_ids}"
  end
end
